### ISSUE TITLE
Работа с панелью внутри Docker

### ISSUE THREAD

**Issue by crtmitchn** [kutovoys/marzban-torrent-blocker#2]
Присутствует ли возможность работы с 3x-ui поднятым в докере? Пытался что-то предпринять, но особо не получилось, дал проге доступ к логам панельки из докеровского тома, вроде всё схватилось, но видимого результата нет

**Comment by kutovoys** [comment]
Приветствую.
Теоретически должно работать с любыми Xray-подобными панелями. С 3x-UI конкретно не проверял, но нужно вытащить логи xray на хост, и дальше уже запускать torrent-blocker на этих логах. 
Ну и главное настроет метку bittorrent трафика. Чтобы в логе были данные метки.

**Comment by crtmitchn** [comment]
Делал все по инструкции, но в логах я данного тега так и не заметил, либо оно у меня попросту не работает, либо трафик как-то мимо всё же идёт

**Comment by kutovoys** [comment]
> Делал все по инструкции, но в логах я данного тега так и не заметил, либо оно у меня попросту не работает, либо трафик как-то мимо всё же идёт

Еще должен быть обязательно включен sniffing в xray конфиге для протокола.
